import { TemplateTheme } from "./types";

export const themes: Record<string, TemplateTheme> = {
  "pink-floral": {
    name: "pink-floral",
    label: "Pink Floral",
    description: "Romântico & Elegante",
    envelope: {
      base: "#F7F0E8",
      topFlap: "/images/top.png",
      bottomFlap: "/images/bottom.png",
    },
    bg: "#FFF8F3",
    cardBg: "#FFFFFF",
    cardBorder: "rgba(201,169,98,0.13)",
    primary: "#8B1A4A",
    secondary: "#8B5E6B",
    accent: "#C9A962",
    textPrimary: "#8B1A4A",
    textSecondary: "#8B5E6B",
    textMuted: "rgba(139,94,107,0.5)",
    displayFont: "'Great Vibes', cursive",
    bodyFont: "'Cormorant Garamond', serif",
    scriptFont: "'Great Vibes', cursive",
    ctaPrimaryBg: "#C9A962",
    ctaPrimaryText: "#FFFFFF",
    ctaSecondaryBorder: "#8B1A4A",
    ctaSecondaryText: "#8B1A4A",
    ctaRadius: "9999px",
    monogramColor: "rgba(255,255,255,0.8)",
    tapTextColor: "rgba(255,255,255,0.8)",
  },
  "modern-minimal": {
    name: "modern-minimal",
    label: "Modern Minimal",
    description: "Limpo & Sofisticado",
    envelope: {
      base: "#F7F0E8",
      topFlap: "/images/top.png",
      bottomFlap: "/images/bottom.png",
    },
    bg: "#FAFAF8",
    cardBg: "transparent",
    cardBorder: "rgba(212,175,55,0.25)",
    primary: "#2C2C2C",
    secondary: "#666666",
    accent: "#D4AF37",
    textPrimary: "#2C2C2C",
    textSecondary: "#999999",
    textMuted: "rgba(153,153,153,0.5)",
    displayFont: "'Playfair Display', serif",
    bodyFont: "'Cormorant Garamond', serif",
    ctaPrimaryBg: "#2C2C2C",
    ctaPrimaryText: "#FAFAF8",
    ctaSecondaryBorder: "#D4AF37",
    ctaSecondaryText: "#D4AF37",
    ctaRadius: "0px",
    monogramColor: "rgba(44,44,44,0.6)",
    tapTextColor: "rgba(44,44,44,0.6)",
  },
  "boho-chic": {
    name: "boho-chic",
    label: "Boho Chic",
    description: "Rústico & Natural",
    envelope: {
      base: "#F7F0E8",
      topFlap: "/images/top.png",
      bottomFlap: "/images/bottom.png",
    },
    bg: "#F5EDE4",
    cardBg: "rgba(255,255,255,0.5)",
    cardBorder: "rgba(160,113,90,0.13)",
    primary: "#A0715A",
    secondary: "#8B7355",
    accent: "#8B9A7A",
    textPrimary: "#A0715A",
    textSecondary: "#8B7355",
    textMuted: "rgba(139,115,85,0.38)",
    displayFont: "'Homemade Apple', cursive",
    bodyFont: "'Libre Baskerville', serif",
    scriptFont: "'Homemade Apple', cursive",
    ctaPrimaryBg: "#A0715A",
    ctaPrimaryText: "#FFFFFF",
    ctaSecondaryBorder: "#A0715A",
    ctaSecondaryText: "#A0715A",
    ctaRadius: "9999px",
    monogramColor: "rgba(255,255,255,0.8)",
    tapTextColor: "rgba(255,255,255,0.8)",
  },
  "midnight-elegance": {
    name: "midnight-elegance",
    label: "Midnight Elegance",
    description: "Luxuoso & Dramático",
    envelope: {
      base: "#F7F0E8",
      topFlap: "/images/top.png",
      bottomFlap: "/images/bottom.png",
    },
    bg: "#0A0F1A",
    cardBg: "rgba(255,255,255,0.03)",
    cardBorder: "rgba(255,215,0,0.12)",
    primary: "#FFFFFF",
    secondary: "rgba(255,215,0,0.38)",
    accent: "#FFD700",
    textPrimary: "#FFFFFF",
    textSecondary: "rgba(255,255,255,0.38)",
    textMuted: "rgba(255,255,255,0.19)",
    displayFont: "'Cinzel', serif",
    bodyFont: "'Lora', serif",
    ctaPrimaryBg: "#FFD700",
    ctaPrimaryText: "#0A0F1A",
    ctaSecondaryBorder: "#FFD700",
    ctaSecondaryText: "#FFD700",
    ctaRadius: "0px",
    monogramColor: "rgba(255,215,0,0.6)",
    tapTextColor: "rgba(255,215,0,0.6)",
  },
};
